//Jenkinsfile (Declarative Pipeline)
/* Requires the Docker Pipeline plugin */
pipeline {
    agent  any//{ docker { image 'maven:3.9.6-eclipse-temurin-17-alpine' } }
    environment{
        PATH = "/opt/homebrew/bin/mvn/bin:$PATH"
    }
    stages {
        stage('build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}