//Jenkinsfile (Declarative Pipeline)
/* Requires the Docker Pipeline plugin */
pipeline {
    agent  any//{ docker { image 'maven:3.9.6-eclipse-temurin-17-alpine' } }
    environment{
        PATH = "/opt/homebrew/Cellar/maven/3.9.6/libexec/bin:$PATH"
    }
    stages {
        stage('build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('deploy'){
            steps{
                sh '''
                   cd terraform
                   terraform init
                   terraform apply -var-file=dev.tfvars -auto-approve
                '''
            }
        }
    }
}